/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ma.projet.model.*;
import ma.societe.service.*;
/**
 *
 * @author afaf
 */
public class formula extends javax.swing.JFrame {

    /**
     * Creates new form formulaire
     */
    public formula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelPrenom = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        LabelNom = new javax.swing.JLabel();
        LabelSexe = new javax.swing.JLabel();
        TextPrenom = new javax.swing.JTextField();
        RadioButtonHomme = new javax.swing.JRadioButton();
        RadioButtonFemme = new javax.swing.JRadioButton();
        LabelAdr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAdr = new javax.swing.JTextArea();
        LabelNom1 = new javax.swing.JLabel();
        TextNom = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ButtonAjouter = new javax.swing.JButton();
        ButtonModifier = new javax.swing.JButton();
        ButtonSupprimer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        ButtonActualiser = new javax.swing.JButton();
        ButtonRechercher = new javax.swing.JButton();
        TextRe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        LabelPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPrenom.setText("Prenom");

        TextId.setEditable(false);
        TextId.setBackground(java.awt.SystemColor.controlHighlight);
        TextId.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        TextId.setForeground(new java.awt.Color(204, 204, 204));
        TextId.setBorder(null);
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });

        LabelNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNom.setText("Nom");

        LabelSexe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelSexe.setText("Sexe");

        TextPrenom.setBackground(java.awt.SystemColor.controlHighlight);
        TextPrenom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TextPrenom.setBorder(null);

        RadioButtonHomme.setBackground(java.awt.SystemColor.activeCaption);
        buttonGroup1.add(RadioButtonHomme);
        RadioButtonHomme.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RadioButtonHomme.setText("Homme");
        RadioButtonHomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonHommeActionPerformed(evt);
            }
        });

        RadioButtonFemme.setBackground(java.awt.SystemColor.activeCaption);
        buttonGroup1.add(RadioButtonFemme);
        RadioButtonFemme.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RadioButtonFemme.setText("Femme");
        RadioButtonFemme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFemmeActionPerformed(evt);
            }
        });

        LabelAdr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelAdr.setText("Adresse");

        TextAdr.setBackground(java.awt.SystemColor.controlHighlight);
        TextAdr.setColumns(20);
        TextAdr.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        TextAdr.setRows(5);
        jScrollPane1.setViewportView(TextAdr);

        LabelNom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNom1.setText("Id");

        TextNom.setBackground(java.awt.SystemColor.controlHighlight);
        TextNom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TextNom.setBorder(null);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        ButtonAjouter.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAjouter.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ajouter.jpg"))); // NOI18N
        ButtonAjouter.setText("Ajouter");
        ButtonAjouter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ButtonAjouter.setBorderPainted(false);
        ButtonAjouter.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterActionPerformed(evt);
            }
        });

        ButtonModifier.setBackground(new java.awt.Color(255, 255, 255));
        ButtonModifier.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/modifier1.jpg"))); // NOI18N
        ButtonModifier.setText("Modifier");
        ButtonModifier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonModifier.setBorderPainted(false);
        ButtonModifier.setPreferredSize(new java.awt.Dimension(115, 29));
        ButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModifierActionPerformed(evt);
            }
        });

        ButtonSupprimer.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSupprimer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ButtonSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/supprimer1.jpg"))); // NOI18N
        ButtonSupprimer.setText("Supprimer");
        ButtonSupprimer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSupprimer.setBorderPainted(false);
        ButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSupprimerActionPerformed(evt);
            }
        });

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        tabledata.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabledata);

        ButtonActualiser.setBackground(new java.awt.Color(255, 255, 255));
        ButtonActualiser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ButtonActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/actualiser1.jpg"))); // NOI18N
        ButtonActualiser.setText("Actualiser");
        ButtonActualiser.setToolTipText("");
        ButtonActualiser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonActualiser.setBorderPainted(false);
        ButtonActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(ButtonActualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(ButtonActualiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(ButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonModifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        ButtonRechercher.setBackground(new java.awt.Color(255, 255, 255));
        ButtonRechercher.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ButtonRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ajouter.jpg"))); // NOI18N
        ButtonRechercher.setText("Rechercher");
        ButtonRechercher.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonRechercher.setBorderPainted(false);
        ButtonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRechercherActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gestion des clients");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioButtonHomme)
                                .addGap(35, 35, 35)
                                .addComponent(RadioButtonFemme))
                            .addComponent(jScrollPane1)
                            .addComponent(TextPrenom)
                            .addComponent(TextNom)
                            .addComponent(TextId))
                        .addGap(497, 497, 497)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextRe, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(841, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(ButtonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextRe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonHomme)
                    .addComponent(RadioButtonFemme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(837, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed
private void deplace(int i)
{
    TextId.setText(dt.getValueAt(i,0).toString());
    TextNom.setText(dt.getValueAt(i,1).toString());
    TextPrenom.setText(dt.getValueAt(i,2).toString());
    if(dt.getValueAt(i, 3).toString().equals("F"))
    {buttonGroup1.setSelected(RadioButtonFemme.getModel(),true);}
    else
    {buttonGroup1.setSelected(RadioButtonHomme.getModel(),true);} 
    TextAdr.setText(dt.getValueAt(i,4).toString());
}
    private void ButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterActionPerformed
         // TODO add your handling code here:
        clientTransaction A=new clientTransaction();
        A.Create(new Client(TextNom.getText(),TextPrenom.getText(),sexe,TextAdr.getText()));
        JOptionPane.showMessageDialog(null, "successfully added");
    }//GEN-LAST:event_ButtonAjouterActionPerformed

    private void ButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModifierActionPerformed
        // TODO add your handling code here:
        clientTransaction A=new clientTransaction();
        if (JOptionPane.showConfirmDialog(null,"confirmer la modification","modifier client",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        if(A.Update(new Client(Integer.valueOf(TextId.getText()),TextNom.getText(),TextPrenom.getText(),sexe,TextAdr.getText())))
        JOptionPane.showMessageDialog(null, "successfully edited");
    }//GEN-LAST:event_ButtonModifierActionPerformed

    private void ButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSupprimerActionPerformed
        // TODO add your handling code here:
        clientTransaction A=new clientTransaction();
        if (JOptionPane.showConfirmDialog(null,"are you sure you want to delete this customer?","supprimer client",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
                
        if(TextId.getText().length()!=0)
        {A.delete(TextId.getText());
        JOptionPane.showMessageDialog(null,"customer deleted");}
        //else 
            //JOptionPane.showMessageDialog(null,"entrez l'id svp!");
    }//GEN-LAST:event_ButtonSupprimerActionPerformed

    private void RadioButtonHommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonHommeActionPerformed
        // TODO add your handling code here:
        sexe="H";
    }//GEN-LAST:event_RadioButtonHommeActionPerformed

    private void RadioButtonFemmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFemmeActionPerformed
        // TODO add your handling code here:
        sexe="F";
    }//GEN-LAST:event_RadioButtonFemmeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dt=new DefaultTableModel();
        dt.addColumn("ID");
        dt.addColumn("NOM");
        dt.addColumn("PRENOM");
        dt.addColumn("SEXE");
        dt.addColumn("Adresse");
        tabledata.setModel(dt);
         affiche();
    }//GEN-LAST:event_formWindowOpened

    private void ButtonActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualiserActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         clientTransaction A=new clientTransaction();
         dt.setRowCount(0);
         for(Client c:A.recuperer())
     {
         Object[] o={c.getIdCli(),c.getNom(),c.getPrenom(),c.getSexe(),c.getAdresse()};
         dt.addRow(o);
       
     }
    }//GEN-LAST:event_ButtonActualiserActionPerformed

    private void tabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledataMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        int i=tabledata.getSelectedRow();
        deplace(i);
    }//GEN-LAST:event_tabledataMouseClicked

    private void ButtonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRechercherActionPerformed
        // TODO add your handling code here:
        clientTransaction A=new clientTransaction();
        dt.setRowCount(0);
        ResultSet R;
        {
        R=A.rechercher(TextRe.getText());
        }try {  
         if(R==null)
        {  affiche();
        JOptionPane.showMessageDialog(null,"client introuvable");}  
         Object[] o={R.getInt(1),R.getString(2),R.getString(3),R.getString(4),R.getString(5)};
                dt.addRow(o);   int i=0; deplace(i);       
        } catch (SQLException ex) {
            Logger.getLogger(formula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonRechercherActionPerformed
public void affiche()
{
     clientTransaction A=new clientTransaction();
     for(Client c:A.recuperer())
     {
         Object[] o={c.getIdCli(),c.getNom(),c.getPrenom(),c.getSexe(),c.getAdresse()};
         dt.addRow(o);
       
     }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualiser;
    private javax.swing.JButton ButtonAjouter;
    private javax.swing.JButton ButtonModifier;
    private javax.swing.JButton ButtonRechercher;
    private javax.swing.JButton ButtonSupprimer;
    private javax.swing.JLabel LabelAdr;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JLabel LabelNom1;
    private javax.swing.JLabel LabelPrenom;
    private javax.swing.JLabel LabelSexe;
    private javax.swing.JRadioButton RadioButtonFemme;
    private javax.swing.JRadioButton RadioButtonHomme;
    private javax.swing.JTextArea TextAdr;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextNom;
    private javax.swing.JTextField TextPrenom;
    private javax.swing.JTextField TextRe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabledata;
    // End of variables declaration//GEN-END:variables
private String sexe;
private DefaultTableModel dt;
        }
